In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu121'

In [3]:
print('hello world!')

hello world!


In [1]:
!nvidia-smi

Sat Oct 28 21:08:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 529.08       Driver Version: 529.08       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1200 La... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8     3W /  40W |     94MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [14]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## PyTorch Fundamentals

In [31]:
import torch
import pandas as pd 
import numpy as np

In [2]:
print(torch.__version__)

2.1.0+cu121


In [4]:
!pip install matplotlib

## 1. Introduction to Tensors. 

### creating tensors

In [9]:
#scalar 
scalar = torch.tensor(5)
scalar

tensor(5)

In [10]:
scalar.ndim

0

In [11]:
#getting tensor back as python int 
scalar.item()

5

In [12]:
#Vector 
vector = torch.tensor([5,5])
vector

tensor([5, 5])

In [13]:
vector.ndim

1

In [16]:
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [17]:
vector[0].item()

5

In [18]:
vector[0]

tensor(5)

In [20]:
vector.shape

torch.Size([2])

### Matrix

In [21]:
Matrix = torch.tensor([[4,8],
                      [2,3]])
Matrix

tensor([[4, 8],
        [2, 3]])

In [22]:
Matrix.ndim

2

In [23]:
Matrix.shape

torch.Size([2, 2])

In [24]:
#Slicing on Matrix
Matrix[0] #first row

tensor([4, 8])

In [25]:
Matrix[1] #second row

tensor([2, 3])

In [27]:
Matrix[0][1] #first row, 2nd column

tensor(8)

### Tensor

In [30]:
Tensor = torch.tensor([[[2,3,4],
                      [5,6,7],
                      [0,1,2]]])

Tensor

tensor([[[2, 3, 4],
         [5, 6, 7],
         [0, 1, 2]]])

In [31]:
Tensor.ndim

3

In [32]:
Tensor.shape

torch.Size([1, 3, 3])

In [33]:
#Slicing 
Tensor[0]

tensor([[2, 3, 4],
        [5, 6, 7],
        [0, 1, 2]])

In [5]:
#some examples
A = torch.tensor([[[1,2],
                  [3,4]]])

A

tensor([[[1, 2],
         [3, 4]]])

In [6]:
A.shape

torch.Size([1, 2, 2])

### Random Tensors

In [7]:
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.0630, 0.7859, 0.1351, 0.2005],
        [0.0024, 0.1872, 0.2681, 0.8307],
        [0.7283, 0.3656, 0.9367, 0.6102]])

In [8]:
random_tensor.shape 

torch.Size([3, 4])

In [9]:
random_tensor = torch.rand(1,3,4)

random_tensor

tensor([[[0.4798, 0.3168, 0.1688, 0.4038],
         [0.1909, 0.5011, 0.1945, 0.7437],
         [0.9637, 0.5985, 0.3880, 0.0505]]])

In [10]:
random_tensor.ndim

3

In [13]:
#Creating a random tensor with similar shape of an image!
random_tensor_image = torch.rand(size=(3,244,244)) #Depth, Height, Width. 
random_tensor_image.shape, random_tensor_image.ndim 

(torch.Size([3, 244, 244]), 3)

### Zero, One Tensors 

example: Mask 

In [17]:
#create a tensor with all zeros
zeros = torch.zeros(size=(3,4))

zeros

zeros.ndim

zeros.shape

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

2

torch.Size([3, 4])

In [18]:
#Create a tensor with all ones
ones = torch.ones(size=(3,6))

ones

ones.ndim

ones.shape

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

2

torch.Size([3, 6])

In [19]:
#datatypes
ones.dtype

torch.float32

In [3]:
#creating a zero tensor of size (3,3,3)

zeros = torch.zeros(size=(3,3,3))

zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [4]:
zeros.ndim

3

In [6]:
zeros.shape

torch.Size([3, 3, 3])

### Creating a tensors using range and like 

In [7]:
torch.range(0,10)

C:\Users\karthik.kolluri\AppData\Local\Temp\ipykernel_1008\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
#torch.range() is deprecated! 
# so we should use torch.arange()!

In [9]:
one_to_ten = torch.arange(1,11)

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
step = torch.arange(start=0, end=1000, step=88)

step

tensor([  0,  88, 176, 264, 352, 440, 528, 616, 704, 792, 880, 968])

In [15]:
step = torch.arange(start=1, end=11, step=1)

step

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#reverse ordering
step = torch.arange(start=10, end=1, step=-1)

step

In [17]:
#Creating Tensor using like!
one_to_ten.shape

torch.Size([10])

In [19]:
# I want to create a 10 zeros tensor (Vector)
ten_zeros = torch.zeros_like(input=one_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
ten_ones = torch.ones_like(input=one_to_ten)

ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note:** Tensor Datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning. 

1. Tensors not in right datatype.
2. Tensors not in right Shape.
3. Tensors not in right device.

In [28]:
#Float_32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

float_32_tensor

float_32_tensor.dtype

tensor([3., 6., 9.])

torch.float32

Even we specify dtype as None but it's datatype is float_32

Because In pytorch, default datatype is 'Float_32'

In [30]:
# we can change Float_32(default) to float_16 (anything!) 

float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16) #torch.int

float_16_tensor

float_16_tensor.dtype

tensor([3., 6., 9.], dtype=torch.float16)

torch.float16

In [31]:
# we can change Float_32(default) to Int_32 (anything!) 
# Integers
float_int_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.int32) #torch.int

float_int_tensor

float_int_tensor.dtype

tensor([3, 6, 9], dtype=torch.int32)

torch.int32

When we are creating tensor, we should remember of these three attributes: dtype, device, requires_grad

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, #What data type is the tensor (e.g: float_32, float_16)
                               device=None, # What Device your tensor is on. 
                               # Device-on which device you are running the operation, default-> cpu (cpu or cuda)
                               requires_grad=None) # Whether or not to track the gradients with this tensor operations

## Precision in Computing!

### In computer science, the precision of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value.

### Converting datatypes of Tensors

In [34]:
float_int_tensor = torch.tensor([1,2,3,5])

float_int_tensor.dtype

torch.int64

In [36]:
#converting int tensor to float_16

float_16_tensor = float_int_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

## Getting Information from Tensors (Tensor Attributes)

1. Tensors not right Datatype - To do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right Shape - To do get Shape of a tensor, can use `tensor.shape`
3. Tensors not right Device - To do get info about on which Device, can use `tensor.device` 

In [37]:
#tensor.shape and tensor.size() will output same info

In [38]:
some_tensor = torch.rand((3,4))

some_tensor

tensor([[0.0352, 0.8944, 0.6499, 0.9203],
        [0.7539, 0.6617, 0.9966, 0.9390],
        [0.7422, 0.9957, 0.1653, 0.5026]])

In [39]:
#Size is not a attribute,it's a function 
some_tensor.size 

<function Tensor.size>

In [40]:
some_tensor.size()

torch.Size([3, 4])

In [41]:
some_tensor.shape

torch.Size([3, 4])

In [43]:
#Find out details about some tensor
some_tensor

print(f'Datatype of the tensor: {some_tensor.dtype}')

print(f'Shape of the Tensor: {some_tensor.shape}')

print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.0352, 0.8944, 0.6499, 0.9203],
        [0.7539, 0.6617, 0.9966, 0.9390],
        [0.7422, 0.9957, 0.1653, 0.5026]])

Datatype of the tensor: torch.float32
Shape of the Tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating a tensor (Tensor Operations)

Tensor Operations include: 

1) Additions
2) Substractions
3) Multiplications (element-wise)
4) Division
5) Matrix Mutliplication



In [48]:
#Addition 
A = torch.tensor([1,2,3])

A

scalar = 10 

A = A + scalar 

A

tensor([1, 2, 3])

tensor([11, 12, 13])

In [51]:
#Multiply tensor by 10 
A = torch.tensor([1,2,3])

A

A * 10

tensor([1, 2, 3])

tensor([10, 20, 30])

In [52]:
# substract 10 

A - 10 

tensor([-9, -8, -7])

PyTorch also has built-in funtions (add, sub, mut, div)

In [54]:
#multiply by 10 
torch.mul(A,10)

tensor([10, 20, 30])

In [55]:
#add by 10 
torch.add(A,10)

tensor([11, 12, 13])

## Matrix Mutiplication 

Two main ways of performing multiplication in Neural Network and Deep learning. 

1. Element-wise multiplication (Scalar mutliplication)
2. Matrix multiplication (Dot product)

In [57]:
#Element-wise multiplication 

tensor = torch.tensor([1,2,3,4])

scalar = torch.tensor(8)

tensor * scalar

tensor([ 8, 16, 24, 32])

In [58]:
#Element-wise multiplication 

tensor = torch.tensor([1,2,3,4]) 

tensor * tensor

tensor([ 1,  4,  9, 16])

In [59]:
#Matrix Mutliplication 
tensor = torch.tensor([1,2,3,4]) 
torch.matmul(tensor,tensor)

#Analysis
# tensor = [1,2,3,4]-T (Transpose) Shape -> 4x1 
# tensor = [1,2,3,4] shape -> 1x4
# matmul = tensor-T * tensor  shape -> (1x4) * (4x1) => 1 (scalar)
# 1*1 + 2*2 + 3*3 + 4*4 => 1 + 4 + 9 + 16 => 30 

tensor(30)

In [61]:
1*1 + 2*2 + 3*3 + 4*4 

30

We can also do this same operation with for loop!

In [76]:
tensor = torch.arange(0,100000)
tensor.shape

torch.Size([100000])

In [77]:
%%time
#for loop version (Matrix Multiplication)
sum = 0
for i in tensor:
    sum += i*i
print(sum)

tensor(333328333350000)
CPU times: total: 1.05 s
Wall time: 1.52 s


In [78]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(333328333350000)

In [79]:
#Torch.matmul is optimized operation to do matrix multiplication!

In [4]:
%%time
#Matrix Mutliplication (@) 
# @ -> signifies as matrix multiplication operator!
tensor = torch.arange(0,100000)

#dot product (tensor . tensor)
tensor @ tensor

CPU times: total: 0 ns
Wall time: 928 µs


tensor(333328333350000)

## Matrix Multiplication Rules
There are two main rules that performing matrix multiplication needs to satisfy!!

1. The **inner dimensions** must match: 
* `(3,2) @ (3,2)` -> won't work!
* `(3,2) @ (2,3)` -> will work! 
* `(2,3) @ (3,2)` -> will work!

2. The resulting matrix has the shape of the **outer dimension**
* `(3,2) @ (2,3) -> (3,3)`
* `(2,3) @ (3,2) -> (2,2)`

In [13]:
#Example (Inner dimension won't match)
A = torch.rand(3,2)

B = torch.rand(3,2)

A.shape, B.shape 

torch.matmul(A,B)

(torch.Size([3, 2]), torch.Size([3, 2]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [9]:
A @ B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [10]:
#Example (where Inner dimension are matching!)
A = torch.rand(3,2)

B = torch.rand(2,3)

A.shape, B.shape 

torch.matmul(A,B)

(torch.Size([3, 2]), torch.Size([2, 3]))

tensor([[0.0878, 0.0870, 0.1772],
        [0.2513, 0.2257, 0.4867],
        [0.4424, 0.3825, 0.8440]])

In [11]:
#Example of Outer dimension 
out = torch.matmul(torch.rand(3,2), torch.rand(2,3)) 
out.shape #(3,3)

torch.Size([3, 3])

In [12]:
out = torch.matmul(torch.rand(3,10), torch.rand(10,3)) 
out.shape #(3,3)

torch.Size([3, 3])

## One of the most common errors in deep learning: Shape Errors 

In [23]:
#tensors for Matrix Multiplication 
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[8,10],
                        [9,11],
                        [7,12]])


#torch.mm(tensor_A,tensor_B) torch.mm() is same as torch.matmul() it's an alias for matmul()
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [24]:
tensor_A.shape, tensor_B.shape 

(torch.Size([3, 2]), torch.Size([3, 2]))

#we can use Transpose to fix shape!

A **Transpose** switches axis or dimensions of a given tensor 

In [31]:
tensor_B

tensor_B.shape

tensor([[ 8, 10],
        [ 9, 11],
        [ 7, 12]])

torch.Size([3, 2])

In [30]:
tensor_B_new = tensor_B.T

tensor_B_new

tensor_B_new.shape

tensor([[ 8,  9,  7],
        [10, 11, 12]])

torch.Size([2, 3])

In [34]:
#Matrix Mutliplication 
tensor_result = torch.matmul(tensor_A, tensor_B.T)

tensor_result

tensor_result.shape

tensor([[ 28,  31,  31],
        [ 64,  71,  69],
        [100, 111, 107]])

torch.Size([3, 3])

In [13]:
#The Matrix Mutliplication operation works when tensor B is transposed!
tensor_A = torch.rand((3,2))
tensor_B = torch.rand((3,2))

print(f'Orginal shape of Tensor A : {tensor_A.shape}')
print(f'Orginal shape of Tensor B : {tensor_B.shape}')

#we cannot perform matmul with these tensors
#torch.matmul(tensor_A, tensor_B)

#we need to perform transpose operation to solve this issue!
tensor_B = tensor_B.T

print(f'Transposed shape of tensor B: {tensor_B.shape}')

print(f'Matrix Mutliplication: {tensor_A.shape} @ {tensor_B.shape} --> inner dimension must match!')

output = torch.mm(tensor_A, tensor_B)

print(f'Output shape: {output.shape}')


Orginal shape of Tensor A : torch.Size([3, 2])
Orginal shape of Tensor B : torch.Size([3, 2])
Transposed shape of tensor B: torch.Size([2, 3])
Matrix Mutliplication: torch.Size([3, 2]) @ torch.Size([2, 3]) --> inner dimension must match!
Output shape: torch.Size([3, 3])


## Tensor Aggregation

Finding Min, Max, Mean, Sum etc...

In [20]:
#create a tensor 
#random integers low=0, high=100,size = (100,) elements
tensor = torch.randint(0,100,(100,))

tensor

tensor([23, 25, 99,  7, 31, 83, 81, 83, 43, 42, 73, 76, 99, 33, 43,  6, 97, 55,
        47, 71, 58, 98, 51, 46, 83, 25, 17, 17, 99, 52, 93, 69, 42, 32, 72, 74,
        83, 42, 81, 25, 34, 51, 42, 48,  4, 55, 12, 56, 82, 17, 83, 61, 15, 22,
        47, 12, 96, 61, 80, 42,  3, 47, 99, 44, 52, 55, 19, 42, 89, 11, 24, 81,
         3, 26, 82, 18, 98,  6, 10, 17, 62, 40, 11, 56, 39, 70, 45, 97, 75, 10,
        89, 26, 18,  9, 37, 55,  9, 42, 11, 56])

In [22]:
#finding min, max, mean, median, sum
tensor.min()

#same operation
torch.min(tensor)

tensor(3)

tensor(3)

In [23]:
torch.max(tensor)

tensor(99)

In [27]:
#mean (Average)
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [28]:
tensor.dtype #int64 is Long!

torch.int64

In [33]:
#our tensor's datatype is int64, but we need to pass float or complex!
#for that we can change the datatype
torch.mean(tensor.type(torch.float64))

tensor(48.7900, dtype=torch.float64)

In [35]:
#Note: torch.mean() function requires a tensor of float or complex datatype
torch.mean(tensor,dtype=torch.float32)

tensor(48.7900)

In [36]:
tensor.type(torch.float64).mean()

tensor(48.7900, dtype=torch.float64)

In [38]:
#Find the sum
torch.sum(tensor)

#similar operation
tensor.sum()

tensor(4879)

tensor(4879)

## Finding the Positional Min and Max of Tensors

argmin(), argmax()

In [39]:
tensor 

tensor([23, 25, 99,  7, 31, 83, 81, 83, 43, 42, 73, 76, 99, 33, 43,  6, 97, 55,
        47, 71, 58, 98, 51, 46, 83, 25, 17, 17, 99, 52, 93, 69, 42, 32, 72, 74,
        83, 42, 81, 25, 34, 51, 42, 48,  4, 55, 12, 56, 82, 17, 83, 61, 15, 22,
        47, 12, 96, 61, 80, 42,  3, 47, 99, 44, 52, 55, 19, 42, 89, 11, 24, 81,
         3, 26, 82, 18, 98,  6, 10, 17, 62, 40, 11, 56, 39, 70, 45, 97, 75, 10,
        89, 26, 18,  9, 37, 55,  9, 42, 11, 56])

In [40]:
tensor.argmin()

tensor(60)

In [41]:
tensor[60]

tensor(3)

In [42]:
#Argmin ---> Argmin will returns the index of minimum value in the tensor

In [43]:
tensor.argmax()

tensor(2)

In [44]:
torch.argmax(tensor)

tensor(2)

In [45]:
tensor[2]

tensor(99)

## Reshaping, Stacking, Squeezing, UnSqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape!

* View - return a view of an input tensor of certain shape but keep the same memory as the orginal tensor.

* Stacking - combine the multiple tensors - on top of each other (vstack - vertically stacking) or side by side (hstack - horizontal stacking)

  -> concatenates a sequence of tensors along a new dimension.

* Squeeze - removes all `1` dimensions from a tensor.

* Unsqueeze - add a `1` dimension to a target tensor.

* Permute -  Return a view of the input with dimensions permuted (swapped) in a certain way.

In [6]:
#let's create a tensor 

x = torch.arange(1.,10)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [7]:
#Add a extra dimension 
#Note: keep in mind, our desired shape should compatible with orginal shape
x_reshaped = x.reshape(1,7)
x_reshaped

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [8]:
x_reshaped = x.reshape(1,9)
x_reshaped

# [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]
# here we can see, we just added a single dimension  

#reshape(1,9) -> 1 row and 9 columns

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [10]:

## we are changing the shape to reshape (9,1) -> 9 rows and 1 column
x_reshaped = x.reshape(9,1)
x_reshaped

x_reshaped.shape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

torch.Size([9, 1])

In [12]:
x = torch.arange(1,19)

x 

x.shape

#here we have single dimension tensor with 18 elements in it!
#It's shape is 1 row, 18 columns

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

torch.Size([18])

In [13]:
#I want to reshape it into 2 rows 9 columns
x_reshaped = x.reshape((2,9))

x_reshaped

x_reshaped.shape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18]])

torch.Size([2, 9])

In [23]:
#Change the view!
x_org = torch.arange(1,19)

x_org

x_org.shape

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

torch.Size([18])

In [24]:
z = x_org.view((2,9))

z 

z.shape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18]])

torch.Size([2, 9])

In [17]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
#View is similar to reshape 
# view shares the memory with orginal tensor 
# z is different view of orginal tensor x. 
#So z shares the same memory as what x does! 

In [25]:
#Let's examplify this! 
# So, changing z, changes x. (because a view of a tensor shares the same memory as the original tensor!) 
#Bascially it's a shallow copy of orginal tensor! so if we change something it will reflect it int the original tensor
#Remember it 

#example 
#let's just change the first element of z (view of x)
z

#reassigning 1 with 1000
z[0,0] = 1000

z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18]])

tensor([[1000,    2,    3,    4,    5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14,   15,   16,   17,   18]])

In [27]:
#This re-assignment will reflect also on x (org tensor)
z, x_org

(tensor([[1000,    2,    3,    4,    5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14,   15,   16,   17,   18]]),
 tensor([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
           13,   14,   15,   16,   17,   18]))

### Stacking 

stack some tensors on top of each other or side by side !

In [31]:
x = torch.arange(1,6)

x

x.shape

tensor([1, 2, 3, 4, 5])

torch.Size([5])

In [32]:
x_stacked = torch.stack(x,dim=0)

#must be tuple of Tensors, not a Tensor 
#that means we need to provide List of Tensors!

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [35]:
x_stacked = torch.stack([x,x],dim=0)

#we stacked x twice in vertically
x_stacked

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [36]:
x_stacked = torch.stack([x,x,x,x,x],dim=0)

#we stacked x twice in vertically
#if we provide dim=0 that means it will stack in row. stacks in vertically way.
x_stacked

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [37]:
#if we provide dim=1 that means it will stack in columns. stacks in horizontal way.
x_stacked = torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]])

In [38]:
#We also have other function to perform stacking()
# vstack() -> performs stacking vertically that means we can stack one tensor on top another
# hstack() -> performs stacking horizontally that means we can stack one tensor beside another

In [39]:
x_org = torch.arange(1,6)

x_org

x_org.shape

tensor([1, 2, 3, 4, 5])

torch.Size([5])

In [40]:
#torch.vstack() -> input: Tensors (list of tensors)
#Stack tensors in sequence vertically (row wise).
x_vstacked = torch.vstack([x_org,x_org])

x_vstacked

x_vstacked.shape

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

torch.Size([2, 5])

In [43]:
#torch.hstack() -> input: Tensors (list of tensors)
#Stack tensors in sequence horizontally (column wise).
x_hstacked = torch.hstack([x_org,x_org])

x_hstacked

x_hstacked.shape

TypeError: expected Tensor as element 0 in argument 0, but got list

## Squeeze 

torch.squeeze() -> removes all single dimensions from a target tensor.

In [53]:
x_org = torch.arange(1,10,dtype=torch.float64)

x_org = x_org.reshape((1,9))

x_org

x_org.shape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float64)

torch.Size([1, 9])

In [58]:
x_squeezed = x_org.squeeze()

x_squeezed

x_squeezed.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

torch.Size([9])

In [55]:
#Squeeze will remove all single dimensions from target tensor
#example: 
#x_org = tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float64)
#torch.Size([1, 9])
#x_org size is [1,9] 
#After squeezing, it will remove single dimensions from x_org 
#so output size will be [9]

#if x_org size is [1,1,9]
# after squeezing, output size will be [9], two single 1 dimensions will be removed! 

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float64)

In [63]:
x_org = torch.zeros((1,1,9))

print(f'Orginal tensor: {x_org}')

print(f"\nOrginal tensor's shape: {x_org.shape}") 

#Remove extra dimensions from x_org
x_squeezed = x_org.squeeze()

print(f'\nSqueezed tensor: {x_squeezed}')

print(f"\nSqueezed tensor's shape: {x_squeezed.shape}")


Orginal tensor: tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

Orginal tensor's shape: torch.Size([1, 1, 9])

Squeezed tensor: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

Squeezed tensor's shape: torch.Size([9])


## Unsqueeze

unsqueeze() -> adds a single dimensions to a target tensor at a specific dim (dimension)

In [65]:
x_org = torch.zeros((9))

x_org

x_org.shape

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

torch.Size([9])

In [68]:
#we can add single dimension to x_org (as many we want!)
print(f"Orginal tensor: {x_org}")

print(f"\nOrginal tensor's shape : {x_org.shape}")

#adding single dimension (dim=0) -> on row
x_unsqueezed = x_org.unsqueeze(dim=0)

print(f"\nUnsqueezed tensor: {x_unsqueezed}")

print(f"\nUnsqueezed tensor: {x_unsqueezed.shape}")

Orginal tensor: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

Orginal tensor's shape : torch.Size([9])

Unsqueezed tensor: tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Unsqueezed tensor: torch.Size([1, 9])


## Permute 

permute() -> rearranges the dimensions of a target tensor in a specific order. 

One of the common places, you will be using Permute is with Images

In [71]:
x_org = torch.rand((244, 244, 3)) #[height, width, depth(color_channels)]

##Permute the orginal tensor to rearrange the axis or (dim) order!

x_permuted = x_org.permute((2,0,1)) #Shifts axis 0->1, 1->2, 2->0

x_permuted.shape

torch.Size([3, 244, 244])

In [75]:
print(f"Orginal shape: {x_org.shape}")

print(f"\nNew Shape: {x_permuted.shape}") #[color_channels, Height, Width]

Orginal shape: torch.Size([244, 244, 3])

New Shape: torch.Size([3, 244, 244])


In [78]:
#### Note: Permute() -> view the new arrangment of tensor shape
# so it will use same memory of target tensor.
# if we do reassignment on permuted tensor, changes will reflect on original tensor!

In [83]:
#re-assigned 
x_permuted[0,0,0] = 999

In [85]:
x_org[0,0,0], x_permuted[0,0,0]

(tensor(999.), tensor(999.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [88]:
#create a tensor 
# [9] elements -> [[[],[],[]]]
x = torch.arange(1,10).reshape((1,3,3))

x

x.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.Size([1, 3, 3])

In [91]:
#Let's Index on our new tensor 
x

#x[0] -> this is gonna index first bracket! (dim=0)
x[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
#lets index on the middle bracket (dim=1)
x[0][0] 

tensor([1, 2, 3])

In [96]:
#similar operation
x[0,0]

tensor([1, 2, 3])

In [97]:
#Let's index on most inner bracket! (dim=2)
x[0][0][0]

tensor(1)

In [99]:
x[0][2][2]

tensor(9)

In [100]:
#You can also use ":" to select "all" of a target dimension 
x[:,0]

tensor([[1, 2, 3]])

In [102]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension 
#x[depth, rows, column]
x[:,:,1] #1st column

tensor([[2, 5, 8]])

In [104]:
#Get all values of 0th dimension but only the 1 index value of 1st and 2nd dimension 
x[:, 1, 1]

tensor([5])

In [105]:
x[0, 0, :]

tensor([1, 2, 3])

In [109]:
#Index on x to return 9 
x[0][2][2]

tensor(9)

In [125]:
#Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch and Numpy

Numpy is a popular scientific python numerical computing library. 

And because of this, PyTorch has functionality to interact with it.  

* Intially Data is in Numpy, want in PyTorch Tensor -> 'torch.from_numpy(ndarray)'

* PyTorch Tensor to Numpy array -> 'torch.tensor.numpy()' 

In [9]:
#Numpy array to tensor 
import torch 
import numpy as np

array = np.arange(1.0,8.0)

array

type(array)

array([1., 2., 3., 4., 5., 6., 7.])

numpy.ndarray

In [11]:
#converting it into pytorch tensor
tensor = torch.from_numpy(array)

tensor

type(tensor)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

torch.Tensor

#### Note: Numpy array's default datatype is 'float64' and 
#### PyTorch tensor's default datatype is 'float32'... 
#### when you convert from numpy array to tensor, it will make tensor with float64


In [15]:
#default datatype
torch.arange(1.0,8.0).dtype

torch.float32

In [17]:
# Warning: when converting from numpy -> pytorch,
# pytorch reflects numpy's default datatype of float64. unless specified otherwise 

In [19]:
### Changing the value of numpy array, does that change will impact on tensor!
array

array = array + 1 

array

array([1., 2., 3., 4., 5., 6., 7.])

array([2., 3., 4., 5., 6., 7., 8.])

In [20]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [21]:
# Note: you can see tensor has no impact when numpy array was changed! 
# so we can say that tensor was created in another memory location

In [25]:
#Tensor to numpy array 
tensor = torch.ones(7)

tensor

tensor.dtype

type(tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])

torch.float32

torch.Tensor

In [27]:
numpy_array = tensor.numpy()

numpy_array

numpy_array.dtype

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

dtype('float32')

In [28]:
#Change the tensor, what happens to 'numpy_array'
tensor = tensor + 1 

tensor 

tensor([2., 2., 2., 2., 2., 2., 2.])

In [29]:
numpy_array

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [30]:
#That means they don't share memory!

## Reproducbility (Trying to take random out of random)

In short how neural network learns: 

'start with random numbers' -> tensor operation -> update random numbers to try and make them better representation of data -> again -> again -> again ....

To reduce the randomness in neural networks and PyTorch comes a concept of **random seed** 

Essentially what the random seed does is 'flavour' the randomness!

In [32]:
torch.rand(3,3)

tensor([[0.8284, 0.1811, 0.2566],
        [0.3302, 0.2041, 0.9313],
        [0.3197, 0.7942, 0.5014]])

In [33]:
torch.rand(3,3)

tensor([[0.1799, 0.6213, 0.6339],
        [0.7754, 0.5735, 0.8836],
        [0.0504, 0.9115, 0.7943]])

In [ ]:
#Everytime we get random numbers!  

In [34]:
#psuedo randomness -> generated randomness!

In [37]:
import torch

#create two random tensors
random_tensor_A = torch.rand((3,4))
random_tensor_B = torch.rand((3,4))


random_tensor_A

random_tensor_B

print(random_tensor_A == random_tensor_B)

tensor([[0.3741, 0.8869, 0.8357, 0.7385],
        [0.3695, 0.9953, 0.8811, 0.9889],
        [0.2801, 0.8135, 0.5623, 0.2242]])

tensor([[0.5025, 0.1573, 0.9214, 0.4304],
        [0.6659, 0.9596, 0.5949, 0.6834],
        [0.0392, 0.3951, 0.9399, 0.8519]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [40]:
#Let's make some random but reproducible tensors

#set the random seed!
RANDOM_SEED = 42  
torch.manual_seed(RANDOM_SEED)


#create some random tensors 
random_tensor_A = torch.rand((3,4))

torch.manual_seed(RANDOM_SEED)

random_tensor_B = torch.rand((3,4))

random_tensor_A

random_tensor_B

random_tensor_A == random_tensor_B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Extra Resources: 
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPUs -> faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good). 

hunky dory -> fine, going well.

### 1. Getting a GPU 

1. **Easiest** - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment!
   
    See this blog post to see which GPU hardware to get...
    Best GPU for Deep learning: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

3. Use Cloud Computing - GCP, AWS, Azure, ect....
    These services allow you to rent computers on the cloud and access them!


* For 2, 3 Options. Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer the Pytorch setup documentation!

In [43]:
!nvidia-smi 

Sun Nov  5 12:34:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 529.08       Driver Version: 529.08       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1200 La... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P8     3W /  35W |     88MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 2. Check for GPU access with PyTorch

In [1]:
#check for GPU access with PyTorch.
import torch

torch.cuda.is_available()

True

In [2]:
#Setup Device Agnostic Code
device = "cuda" if torch.cuda.is_available() else  "cpu"

device

'cuda'

set device to CUDA, if there is a gpu available, or else it will set it to cpu.

In [3]:
#Count no of devices (GPUs)   
torch.cuda.device_count()  

1

extra resources about device agnostic code - https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

## 3. How actually we can use the GPU
### Puttting tensors and models on GPU. 

The reason why we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [6]:
#create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [11]:
#Move tensor to GPU (if available)

device = "cuda" if torch.cuda.is_available() else "cpu"

device

#tensor which is on cpu
tensor, tensor.device

tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**cuda:0**, 0 is the index of the GPU that we are using!. 

we have 1 GPU, it's index is 0.

### 4. Moving Tensor back to the CPU

because, Numpy only works with CPU. so you need to get back from GPU to CPU to perform such operations.

In [15]:
# If the tensor is on GPU, can't transform it to Numpy. 
tensor_on_gpu

tensor_on_gpu.numpy()

tensor([1, 2, 3], device='cuda:0')

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [16]:
## We will get device errors!

In [19]:
#To fix the GPU tensor with Numpy issue. we can first set it to the CPU.
tensor_on_gpu

tensor_back_on_cpu = tensor_on_gpu.cpu()

tensor_back_on_cpu

tensor_back_on_cpu.device

tensor([1, 2, 3], device='cuda:0')

tensor([1, 2, 3])

device(type='cpu')

In [21]:
#Now it is working! 
tensor_back_on_cpu.numpy()

array([1, 2, 3], dtype=int64)