In [ ]:
import torch

In [ ]:
torch.__version__

'1.13.0+cu116'

# Tensors

## Empty 

The tensor.empty() function returns the tensor that is filled with uninitialized data and the tensor shape is defined by the variable argument called size.

In [ ]:
x = torch.empty(1) #scalar

In [ ]:
x

tensor([2.2061e-35])

In [ ]:
y = torch.empty(4) # 1d vector
y

tensor([2.2061e-35, 0.0000e+00, 1.5975e-43, 1.3873e-43])

In [ ]:
y = torch.empty((2,3)) #2d matrix

In [ ]:
y

tensor([[2.2064e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])

In [ ]:
z = torch.empty(3,2,3) #3d matrixx

In [ ]:
z

tensor([[[ 2.1138e-35,  0.0000e+00, -7.5280e+18],
         [ 4.5623e-41, -7.4195e+18,  4.5623e-41]],

        [[-7.4184e+18,  4.5623e-41, -7.4086e+18],
         [ 4.5623e-41, -7.4398e+18,  4.5623e-41]],

        [[-7.5297e+18,  4.5623e-41, -2.3111e+21],
         [ 4.5623e-41, -7.4094e+18,  4.5623e-41]]])

Random

In [ ]:
x = torch.rand(2,2)

In [ ]:
x

tensor([[0.5796, 0.6060],
        [0.8716, 0.3679]])

In [ ]:
y = torch.rand(2)
y

tensor([0.5886, 0.4884])

## Zeros

In [ ]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

## Similarly !!! Ones

In [ ]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.ones((2,2),dtype=torch.int)

In [ ]:
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [ ]:
x.dtype

torch.int32

In [ ]:
x = torch.ones((2,2),dtype=torch.float16)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [ ]:
x.dtype

torch.float16

In [ ]:
x.size()

torch.Size([2, 2])

## Tensor

In [ ]:
x = torch.tensor([2.2,0.15])
x

tensor([2.2000, 0.1500])

In [ ]:
x.dtype

torch.float32

# Tensor Operation 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
print(x)
y

tensor([[0.1720, 0.9929],
        [0.3049, 0.1244]])


tensor([[0.7373, 0.8089],
        [0.0938, 0.7091]])

In [ ]:
#Add (element-wise addition)
z = x+y 
z

tensor([[0.9093, 1.8019],
        [0.3987, 0.8335]])

Same add operation, but with torch add !!

In [ ]:
z = torch.add(x,y)
z

tensor([[0.9093, 1.8019],
        [0.3987, 0.8335]])

Inplace ADD !!

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
#Inplace ADD
y = torch.add_(x) 
#this will modify our y and add all of the elements to our y 

In pytorch, if we have _ underscore after every method !! is an inplace operation !!

- This will modify the variable that it is applied on !!

In [ ]:
#sub 
z = torch.sub(x,y) #element-wise substraction
z

tensor([[ 0.6681,  0.1341],
        [-0.5065, -0.1572]])

In [ ]:
#mul
z = torch.mul(x,y)
z

tensor([[0.0365, 0.4530],
        [0.1512, 0.2840]])

In [ ]:
#division
z = torch.div(x,y)
z

tensor([[14.1715,  1.2200],
        [ 0.2939,  0.7453]])

## Tensor Slicing !!

In [ ]:
x = torch.rand(5,3)
x

tensor([[0.0240, 0.4017, 0.0132],
        [0.3680, 0.2301, 0.3683],
        [0.1771, 0.0623, 0.8601],
        [0.5766, 0.5273, 0.4449],
        [0.3009, 0.7220, 0.2876]])

In [ ]:
#we want to slice all rows but single column !!
print(x[:,0])

tensor([0.0240, 0.3680, 0.1771, 0.5766, 0.3009])


In [ ]:
# all columns but single row
x[0,:]

tensor([0.0240, 0.4017, 0.0132])

In [ ]:
# getting value of 1st row's 1st column element !!
x[0,0]

tensor(0.0240)

In [ ]:
#if we want item from tensor, we can use item() method !!
x[0,0].item()

0.023952186107635498

## Reshaping Tensor 

In [ ]:
#if we want to reshape, the tensor, then we have to use view() method!!

x = torch.rand(4,4)
print('Before Reshaping: (4X4)')
print(x)
print()
#4*4 = 16 single row vector
print('After Reshaping: (16X1)')
y = x.view(16) 
y

#NOTE: Element should match !!

Before Reshaping: 
tensor([[0.9767, 0.8641, 0.8981, 0.4910],
        [0.2709, 0.3989, 0.4079, 0.8920],
        [0.8526, 0.8582, 0.6788, 0.1828],
        [0.4798, 0.6732, 0.3957, 0.6828]])

After Reshaping: 


tensor([0.9767, 0.8641, 0.8981, 0.4910, 0.2709, 0.3989, 0.4079, 0.8920, 0.8526,
        0.8582, 0.6788, 0.1828, 0.4798, 0.6732, 0.3957, 0.6828])

In [ ]:
x = torch.rand(4,4) 

y = x.view(-1,8)

print(y)

print(y.size())

#if we give single value, and -1 Then  pytorch will take care about the size

tensor([[0.4762, 0.8864, 0.0985, 0.0527, 0.8507, 0.3539, 0.7927, 0.1851],
        [0.5630, 0.9309, 0.1980, 0.5913, 0.5360, 0.9645, 0.6356, 0.3951]])
torch.Size([2, 8])


In [ ]:
y = x.view(-1,-1)

RuntimeError: ignored

## Numpy to Tensor 

In [ ]:
import numpy as np

In [ ]:
a = np.ones(5)

In [ ]:
b = torch.from_numpy(a)

In [ ]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

## Check GPU 

In [ ]:
torch.cuda.is_available()

False

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  y = y.to(device)
  #operation
  z = x + y
  z.numpy()

  z = z.to('cpu')